In [1]:
#Importing necessary libraries
import pandas as pd
import timeit
from itertools import combinations 
import multiprocessing as mp
import time
import numpy as np
import math


In [2]:
#Read the country - ASN matrix file
filename = "final-v2"
df_fin = pd.read_csv("Data/WrittenData/output-df-" + filename + ".txt", sep=",", header=None)
df_fin.columns = ["ASN","to_IP","latency", "Country"]

In [3]:
df_final = df_fin.pivot_table('latency', 'Country', 'ASN')

In [4]:
df = pd.DataFrame(df_final)
print(df.min())

ASN
AS12552      18.534644
AS12637       9.629652
AS12676       8.860601
AS12824       7.690545
AS12859       4.008415
AS12876       5.202024
AS12993       0.962479
AS13287       8.105701
AS15401      13.821171
AS15510      10.032219
AS15598       8.474318
AS15685       1.169748
AS15699       7.258456
AS15817      14.708679
AS15826      20.070785
AS15879       4.843850
AS15954       3.719392
AS15987      19.421554
AS16125       4.759442
AS16245       3.410800
AS16276      43.160442
AS16347      11.569609
AS196745     16.424801
AS197019      6.074332
AS197540     11.189430
AS197595     15.432857
AS198068      2.831768
AS198171      3.612339
AS198452      3.426078
AS198651      5.511574
               ...    
AS50957       5.457116
AS51088       3.781052
AS51167      12.578684
AS51468       8.766206
AS51815       4.127555
AS51862       8.600476
AS5404        9.034266
AS5430        7.915172
AS5521       10.725613
AS59729      12.448835
AS59816      15.977985
AS60144       3.143132
AS60362

In [5]:
df

ASN                                                   AS12552    AS12637  \
Country                                                                    
Austria                                             36.619357  41.767681   
Belgium                                             50.259722  71.802510   
Bulgaria                                                  NaN        NaN   
Croatia                                                   NaN  18.530777   
Cyprus                                                    NaN        NaN   
Czechia                                                   NaN        NaN   
Denmark                                             26.063465        NaN   
Estonia                                                   NaN        NaN   
Finland                                             23.065994        NaN   
France                                                    NaN  42.549810   
Germany                                             30.222977  54.150232   
Greece                                                    NaN  53.783478   
Hungary                                                   NaN        NaN   
Ireland                                                   NaN        NaN   
Italy                                                     NaN  20.331374   
Latvia                                                    NaN        NaN   
Lithuania                                           66.238023        NaN   
Luxembourg                                                NaN        NaN   
Netherlands                                         38.734046  38.427263   
Poland                                              33.619162        NaN   
Portugal                                                  NaN  42.059881   
Romania                                                   NaN  99.597628   
Slovakia                                                  NaN        NaN   
Slovenia                                                  NaN  16.803651   
Spain                                                     NaN  40.101035   
Sweden                                              18.534644   9.629652   
United Kingdom of Great Britain and Northern Ir...        NaN  43.902021   

ASN                                                    AS12676     AS12824  \
Country                                                                      
Austria                                              26.752958   69.742375   
Belgium                                              12.456738   30.749242   
Bulgaria                                             37.829343   37.680070   
Croatia                                              28.010374         NaN   
Cyprus                                              143.658009         NaN   
Czechia                                              14.394430         NaN   
Denmark                                              19.192033   41.878052   
Estonia                                              33.229430         NaN   
Finland                                              29.330239   55.988755   
France                                               17.585874   39.891105   
Germany                                              12.624867   26.404277   
Greece                                               57.916666   63.704095   
Hungary                                              21.582174         NaN   
Ireland                                              23.771991         NaN   
Italy                                                23.764958   42.759796   
Latvia                                               31.816563         NaN   
Lithuania                                            30.541257         NaN   
Luxembourg                                           10.825364         NaN   
Netherlands                                           8.860601   35.669714   
Poland                                               23.699151    7.690545   
Portugal                                             41.611405         NaN   
R

In [7]:
#Obtain combinations of 4 for all ASN
nASN = df.shape[1]
c = [x for x in combinations(list(range(nASN)), 4) ]
c = list(map(lambda elem: list(elem) , c))


In [8]:
#Getting the sum of min values of latency for selected ASN 
df.iloc[:, [0, 1, 2, 3]].min(1).sum()


755.7543060369551

In [9]:
df2 = df.values
df2

array([[36.61935678, 41.76768146, 26.7529584 , ..., 16.03860851,
        32.7061815 , 60.77371745],
       [50.25972229, 71.80250986, 12.45673754, ...,  9.29827999,
        18.45495327, 10.06376393],
       [        nan,         nan, 37.82934279, ..., 35.23831618,
        41.14655774, 34.10242738],
       ...,
       [        nan, 40.10103493, 41.0909224 , ..., 34.60848367,
        43.52233077,         nan],
       [18.53464441,  9.6296522 , 25.13818168, ..., 24.4464117 ,
        21.65298891, 19.06136325],
       [        nan, 43.90202097, 28.83667301, ..., 28.34315042,
        31.28241986, 18.76360122]])

In [13]:
#Exhaustive enumeration algortihm
def enumerationAlg(listIndex):
    i = listIndex[0]
    j = listIndex[1]
    k = listIndex[2]
    l = listIndex[3]
    return (np.nansum(np.nanmin(df2[:, [i, j, k, l]], axis = 1))) 


In [10]:
len(c)

28342440

In [11]:
import operator as op
from functools import reduce

def ncr(n, r):
    r = min(r, n-r)
    numer = reduce(op.mul, range(n, n-r, -1), 1)
    denom = reduce(op.mul, range(1, r+1), 1)
    return numer / denom

In [12]:
ncr(163,4)

28342440.0

#The number of combinations is same above. Hence, the number of combinations is optimal. 
Do not run below.

In [14]:
#Running the algorithm for the combinations
st = time.time()
results = list(map(enumerationAlg , c))
et = time.time()
print(round(et-st,2))


C:\Users\Karanizer\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: All-NaN slice encountered
  from ipykernel import kernelapp as app


597.21


In [15]:
#Saving the results, they are not attached as they are large in size but as you can see it takes around 10 min
#to run the above code if necessary

data = np.array(results)
np.savez("Data/results", data)
indexes = np.array(c)
np.savez("Data/indexes", indexes)


Start running

In [16]:
#Load the results 
a = np.load("Data/results.npz") #make sure you use the .npz!
b = a['arr_0']
lst = a.files
for item in lst:
    print(item)
    print(a[item])

arr_0
[755.75430604 742.51022534 699.56958401 ... 766.73105924 743.28869096
 734.30081718]


In [17]:
lst = a.files
for item in lst:
    print(item)
    print(a[item])

arr_0
[755.75430604 742.51022534 699.56958401 ... 766.73105924 743.28869096
 734.30081718]


In [18]:
#Load indexes list
a1 = np.load("Data/indexes.npz") #make sure you use the .npz!
b1 = a1['arr_0']
lst = a1.files
for item in lst:
    print(item)
    print(a1[item])

arr_0
[[  0   1   2   3]
 [  0   1   2   4]
 [  0   1   2   5]
 ...
 [158 159 161 162]
 [158 160 161 162]
 [159 160 161 162]]


In [19]:
#maximum latent value
minlatent = np.amin(b)
print(minlatent)

43.70753625622931


In [20]:
#Get position of maxlatent combination
pos = np.where(b == np.amin(b))

In [21]:
pos

(array([22364302, 22425578], dtype=int64),)

In [22]:
#Checking that position in indexes table

print(b1[22364302])
print(b1[22425578])

[ 52  54 122 146]
[ 52  66 122 146]


In [24]:
#Obtaining the ASN and country matrix for corresponding value
df.iloc[:, [52, 66, 122, 146]]

ASN                                                   AS25151     AS30823  \
Country                                                                     
Austria                                             16.601123  106.607949   
Belgium                                             10.129796   15.705225   
Bulgaria                                                  NaN         NaN   
Croatia                                                   NaN         NaN   
Cyprus                                                    NaN         NaN   
Czechia                                                   NaN         NaN   
Denmark                                                   NaN         NaN   
Estonia                                                   NaN         NaN   
Finland                                                   NaN         NaN   
France                                                    NaN         NaN   
Germany                                             10.025316   19.574280   
Greece                                                    NaN         NaN   
Hungary                                                   NaN         NaN   
Ireland                                                   NaN         NaN   
Italy                                                     NaN         NaN   
Latvia                                                    NaN         NaN   
Lithuania                                                 NaN         NaN   
Luxembourg                                                NaN         NaN   
Netherlands                                          3.223430   25.306029   
Poland                                                    NaN         NaN   
Portugal                                                  NaN         NaN   
Romania                                                   NaN         NaN   
Slovakia                                                  NaN         NaN   
Slovenia                                                  NaN         NaN   
Spain                                                     NaN         NaN   
Sweden                                               0.929297   16.653729   
United Kingdom of Great Britain and Northern Ir...   8.684740   22.989454   

ASN                                                   AS47869    AS60610  
Country                                                                   
Austria                                             15.568479  18.288481  
Belgium                                             41.071473  23.973938  
Bulgaria                                                  NaN        NaN  
Croatia                                                   NaN        NaN  
Cyprus                                                    NaN        NaN  
Czechia                                                   NaN        NaN  
Denmark                                                   NaN        NaN  
Estonia                                                   NaN        NaN  
Finland                                                   NaN        NaN  
France                                                    NaN        NaN  
Germany                                             35.957525  26.185254  
Greece                                                    NaN        NaN  
Hungary                                                   NaN        NaN  
Ireland                                                   NaN        NaN  
Italy                                                     NaN        NaN  
Latvia                                                    NaN        NaN  
Lithuania                                                 NaN        NaN  
Luxembourg                                                NaN        NaN  
Netherlands                                          8.734829   6.325226  
Poland                                                    NaN        NaN  
Portugal                                                  NaN        NaN  
Romania                                  

### Calculating the same with NAs filled with mean values ###

In [27]:
#Convert NA to mean to obtain the average values for all countries 
df_final2 = df_final.apply(lambda x: x.fillna(x.mean())) 
df_final2.head()

ASN         AS12552    AS12637     AS12676    AS12824     AS12859    AS12876  \
Country                                                                        
Austria   36.619357  41.767681   26.752958  69.742375   20.700903  23.581590   
Belgium   50.259722  71.802510   12.456738  30.749242   10.999918   7.454970   
Bulgaria  35.928599  42.388357   37.829343  37.680070   41.307183  24.697372   
Croatia   35.928599  18.530777   28.010374  52.739260   29.112300  24.697372   
Cyprus    35.928599  42.388357  143.658009  52.739260  140.625904  24.697372   

ASN         AS12993     AS13287    AS15401    AS15510  ...    AS61272  \
Country                                                ...              
Austria   76.030970   28.567640  29.179260  86.795424  ...  25.025426   
Belgium   35.651291   34.380554  16.864881  35.439629  ...  30.459532   
Bulgaria  59.449729   42.000816  49.284187  54.443460  ...  52.379982   
Croatia   31.595915   42.000816  41.378293  37.552261  ...  27.000162   
Cyprus    31.595915  143.423033  41.378293  37.552261  ...  27.000162   

ASN          AS62000    AS62282     AS62416      AS6724     AS8304     AS8315  \
Country                                                                         
Austria    30.225441  92.248862   65.340133   27.720250  83.395871  17.718057   
Belgium    11.855867  28.136988   39.106969   18.569430  13.062580  31.738229   
Bulgaria   40.181855  27.681254   68.995896   45.403018  29.408301  42.606843   
Croatia    22.432474  27.681254   56.460065   50.835469  29.408301  21.241592   
Cyprus    136.160994  27.681254  144.597993  150.948461  29.408301  21.241592   

ASN           AS8560      AS8893     AS9211  
Country                                      
Austria    16.038609   32.706182  60.773717  
Belgium     9.298280   18.454953  10.063764  
Bulgaria   35.238316   41.146558  34.102427  
Croatia    29.258586   33.511693  25.137273  
Cyprus    147.901064  148.636264  25.137273  

[5 rows x 163 columns]

In [28]:
df_mean = pd.DataFrame(df_final2)
df_mean2 = df_mean.values 

#Exhaustive enumeration algortihm
def enumerationAlg2(listIndex):
    i = listIndex[0]
    j = listIndex[1]
    k = listIndex[2]
    l = listIndex[3]
    return (np.sum(np.min(df_mean2[:, [i, j, k, l]], axis = 1))) 


In [29]:
#Running the algorithm for the combinations
st = time.time()
results = list(map(enumerationAlg2 , c))
et = time.time()
print(round(et-st,2))


323.23


In [30]:
#Saving the results, they are not attached as they are large in size but as you can see it takes around 5 min
#to run the above code if necessary
data = np.array(results)
np.savez("Data/results2", data)

In [31]:
#Load teh results 
a = np.load("Data/results2.npz") #make sure you use the .npz!
b = a['arr_0']
lst = a.files
for item in lst:
    print(item)
    print(a[item])

arr_0
[618.56330311 610.35030459 508.60174455 ... 474.46294547 544.71234578
 480.68513089]


In [32]:
lst = a.files
for item in lst:
    print(item)
    print(a[item])

arr_0
[618.56330311 610.35030459 508.60174455 ... 474.46294547 544.71234578
 480.68513089]


In [33]:
#Load indexes list
a1 = np.load("Data/indexes.npz") #make sure you use the .npz!
b1 = a1['arr_0']
lst = a1.files
for item in lst:
    print(item)
    print(a1[item])

arr_0
[[  0   1   2   3]
 [  0   1   2   4]
 [  0   1   2   5]
 ...
 [158 159 161 162]
 [158 160 161 162]
 [159 160 161 162]]


In [34]:
#maximum latent value
minlatent = np.amin(b)
print(minlatent)

170.86695716375604


In [35]:
#Get position of maxlatent combination
pos = np.where(b == np.amin(b))

In [36]:
pos

(array([22415666], dtype=int64),)

In [37]:
#Checking that position in indexes table

print(b1[22415666])

[ 52  64 107 155]


In [39]:
#Obtaining the ASN and country matrix for corresponding value
df_mean.iloc[:, [52, 64, 107, 155]]

ASN                                                   AS25151     AS29405  \
Country                                                                     
Austria                                             16.601123   23.501301   
Belgium                                             10.129796   22.874447   
Bulgaria                                             8.265617   42.008326   
Croatia                                              8.265617   11.126990   
Cyprus                                               8.265617  155.745399   
Czechia                                              8.265617    6.855647   
Denmark                                              8.265617   34.943398   
Estonia                                              8.265617   45.883477   
Finland                                              8.265617   45.060574   
France                                               8.265617   33.851210   
Germany                                             10.025316   29.295189   
Greece                                               8.265617   43.869191   
Hungary                                              8.265617    5.218637   
Ireland                                              8.265617   48.294018   
Italy                                                8.265617   30.583792   
Latvia                                               8.265617   37.076201   
Lithuania                                            8.265617   28.952443   
Luxembourg                                           8.265617   28.738636   
Netherlands                                          3.223430   22.202929   
Poland                                               8.265617   19.462442   
Portugal                                             8.265617   52.651077   
Romania                                              8.265617   27.436755   
Slovakia                                             8.265617    0.954662   
Slovenia                                             8.265617   11.277749   
Spain                                                8.265617   45.533742   
Sweden                                               0.929297   33.834250   
United Kingdom of Great Britain and Northern Ir...   8.684740   39.585130   

ASN                                                   AS42442    AS62282  
Country                                                                   
Austria                                              6.696137  92.248862  
Belgium                                              3.668655  28.136988  
Bulgaria                                            30.006074  27.681254  
Croatia                                             17.734063  27.681254  
Cyprus                                              17.734063  27.681254  
Czechia                                             19.003633  27.681254  
Denmark                                             17.734063  27.681254  
Estonia                                             17.734063  27.681254  
Finland                                             17.734063  12.761289  
France                                               9.161122  35.682180  
Germany                                              3.769482  37.865944  
Greece                                              36.953586  27.681254  
Hungary                                             17.734063  27.681254  
Ireland                                             22.198919  49.043383  
Italy                                               14.894465  42.278158  
Latvia                                              17.734063   5.814834  
Lithuania                                           17.734063   0.693350  
Luxembourg                                           4.538076  27.681254  
Netherlands                                          8.428873  26.961963  
Poland                                              17.734063  10.300113  
Portugal                                            42.179599  27.681254  
Romania                                  